# ARDUINO_LIBS = Ethernet SPI
BOARD_TAG    = uno
# MONITOR_PORT = /dev/cu.usb*

# On the Mac with IDE 1.0 you might want to set:
#
#   ARDUINO_DIR   = /Applications/Arduino.app/Contents/Resources/Java
#   ARDMK_DIR     = /usr/local
#
# On the Mac with IDE 1.5+ you might want to set:
#
#   ARDUINO_DIR   = /Applications/Arduino.app/Contents/Java
#   ARDMK_DIR     = /usr/local
#
# On Linux, you might prefer:
#
ARDUINO_DIR   = /usr/share/arduino
ARDMK_DIR     = /usr/share/arduino
AVR_TOOLS_DIR = /usr

 #       ARDUINO_LIBS = Ethernet SPI
 #       BOARD_TAG    = uno
 #       MONITOR_PORT = /dev/cu.usb*
 #
 
 #
 # Hopefully these will be self-explanatory but in case they're not:
 #
 #    ARDUINO_LIBS - A list of any libraries used by the sketch (we
 #                   assume these are in $(ARDUINO_DIR)/hardware/libraries
 #                   or your sketchbook's libraries directory)
 #
 #    MONITOR_PORT - The port where the Arduino can be found (only needed
 #                   when uploading)
 #
 #    BOARD_TAG    - The tag for the board e.g. uno or mega
 #                   'make show_boards' shows a list
 include /usr/share/arduino/Arduino.mk
